In [ ]:
import torch 

In [ ]:
scaler = torch.tensor(5)
print(scaler)

tensor(5)


In [ ]:
vector = torch.tensor([1,2,3,4,5,6,7,8,9,10])
print(vector)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [ ]:
matrix = torch.tensor([[1,2,3], 
                      [4,5,6], 
                      [7,8,9]])
print(matrix)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
tensor3d = torch.tensor([[[1,2,3,], [4,5,6]], [[11, 12, 13], [14, 15, 16]]])
print(tensor3d)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 12, 13],
         [14, 15, 16]]])


In [ ]:
from torch import tensor, Tensor

In [ ]:
scaler = tensor(10)
print(scaler)

tensor(10)


In [ ]:
tensor3dd = tensor([[[1,2], [3,4], [5,6]],[[1,2], [3,4], [5,6]],[[1,2], [3,4], [5,6]]])
print(tensor3dd)

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]])


In [ ]:
print(tensor3dd.shape)

torch.Size([3, 3, 2])
